"""End-to-end confirmation (follow-up to code_model_connectivity_smoke_test.py):
run a full code-edit task through the real engine with code_model pointed at
whatever .env/config.yaml actually configure -- OpenRouter's openai_compatible
adapter with the CODE_MODEL_NAME -> FALLBACK_1 -> FALLBACK_2 fallback chain.
Unlike app/openai_compatible_smoke_test.py (which points code_model at
Ollama's own /v1 endpoint to test the adapter's protocol handling in
isolation), this uses config.yaml unmodified: the plan/edit steps are
genuinely generated by a remote OpenRouter model, not local Ollama.

llm stays on native Ollama (planning); code_model does the actual file edit.
push targets the test repo's "origin", which has no remote configured, so a
push failure here is expected and not a sign anything is wrong -- the point
is confirming the *edit* step (plan -> approve -> edit -> test -> commit) ran
through the real OpenRouter call.

Run from the repo root:  python -m app.code_model_e2e_smoke_test
"""
from __future__ import annotations
import copy
import sys
from pathlib import Path

from app.config_loader import load_config
from app.wiring import build_engine, build_ingest, build_retriever
from adapters.llm_ollama import OllamaLLM
from adapters.llm_openai_compatible import OpenAICompatibleLLM
from product.approval import PlanDecision
from product.indexing import index_repo

TEST_REPO = r"C:\Users\Ranjith\AI-Space\forge-test-repo"
TEST_CHECKPOINT_PATH = "./.data/checkpoints_code_model_e2e_smoke_test.db"


def main() -> int:
    cfg = copy.deepcopy(load_config())
    cfg["forge"]["repo_path"] = TEST_REPO
    cfg["retriever"]["collection"] = "forge_code_model_e2e_smoke_test"
    Path(TEST_CHECKPOINT_PATH).unlink(missing_ok=True)
    cfg["engine"]["checkpoint_path"] = TEST_CHECKPOINT_PATH

    print(f"[cfg] code_model.models = {cfg['code_model'].get('models')!r}")
    print(f"[cfg] code_model.base_url = {cfg['code_model'].get('base_url')!r}")

    ingest = build_ingest(cfg)
    retriever = build_retriever(cfg)
    stats = index_repo(ingest, retriever)
    print(f"[ok] indexed {stats['symbols']} chunk(s) across {stats['files']} file(s) from the test repo")

    engine = build_engine(cfg, retriever=retriever)
    if not isinstance(engine.llm, OllamaLLM):
        print(f"[!!] expected engine.llm to be OllamaLLM, got {type(engine.llm).__name__}")
        return 1
    if not isinstance(engine.code_model, OpenAICompatibleLLM):
        print(f"[!!] expected engine.code_model to be OpenAICompatibleLLM, got {type(engine.code_model).__name__}")
        return 1
    print(f"[ok] engine.llm={type(engine.llm).__name__} (native Ollama, planning), "
          f"engine.code_model={type(engine.code_model).__name__} (OpenRouter, editing)")

    result = engine.run_task(
        "Add a short comment above the greet function explaining what it does",
        thread_id="code-model-e2e-smoke",
        approve=lambda plan: PlanDecision("approve"),
        approve_pr=lambda diff, title, body: False,
    )

    if result.get("approved") is not True:
        print(f"[!!] expected approved=True, got {result.get('approved')!r}")
        return 1
    print(f"[ok] plan approved (generated by llm/Ollama-native): title={result['plan'].title!r}")

    edit_results = result.get("edit_results")
    if not edit_results or any(r.get("status") != "ok" for r in edit_results):
        print(f"[!!] expected a successful edit (generated by code_model/OpenRouter), got {edit_results!r}")
        return 1
    print(f"[ok] edit_results (via OpenRouter code_model, real remote call): {edit_results}")
    print(f"[ok] diff:\n{result.get('diff', '')}")

    commit_result = result.get("commit_result")
    print(f"[ok] commit_result={commit_result}")
    push_result = result.get("push_result")
    print(f"[info] push_result={push_result} "
          f"(expected to fail/no-op: {TEST_REPO} has no 'origin' remote configured)")

    print("\nOK. Full task completed with code_model genuinely calling OpenRouter "
          "(fallback chain), llm on native Ollama for planning -- confirms the real "
          "config, not a hand-pointed override.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
