"""Phase 22 acceptance check: with code_model switched to the new
OpenAI-compatible adapter and llm still on native Ollama, run a full task
end to end (plan -> approve -> edit -> test -> commit -> push).

Points code_model at Ollama's own real OpenAI-compatible endpoint
(http://localhost:11434/v1) -- this dev box has no paid hosted API key, so
this proves the adapter speaks the real OpenAI chat-completions/SSE protocol
correctly against a real implementation of it (verified independently
against raw `curl` before this file was written), not a hand-rolled mock.
llm stays on adapters/llm_ollama.py's native /api/chat client the whole
time -- confirmed by type-checking both engine.llm and engine.code_model
below -- so this is a genuine two-adapter mix, not just "point everything at
the same server."

Run from the repo root:  python -m app.openai_compatible_smoke_test
"""
from __future__ import annotations
import copy
import sys
from pathlib import Path
from app.config_loader import load_config
from app.wiring import build_engine, build_ingest, build_retriever
from adapters.llm_ollama import OllamaLLM
from adapters.llm_openai_compatible import OpenAICompatibleLLM
from product.approval import PlanDecision
from product.indexing import index_repo

TEST_REPO = r"C:\Users\Ranjith\AI-Space\forge-test-repo"
TEST_CHECKPOINT_PATH = "./.data/checkpoints_openai_compatible_smoke_test.db"

def main() -> int:
    base_cfg = load_config()
    cfg = copy.deepcopy(base_cfg)
    cfg["forge"]["repo_path"] = TEST_REPO
    cfg["retriever"]["collection"] = "forge_openai_compatible_smoke_test"
    Path(TEST_CHECKPOINT_PATH).unlink(missing_ok=True)
    cfg["engine"]["checkpoint_path"] = TEST_CHECKPOINT_PATH

    # llm: untouched, still the native Ollama adapter.
    # code_model: swapped to the new adapter -- still Ollama under the hood
    # (no paid key on this box), but through the OpenAI-compatible /v1 REST+SSE
    # protocol, a genuinely different code path from adapters/llm_ollama.py.
    cfg["code_model"] = {
        "adapter": "openai_compatible",
        "model": "llama3.2:1b",
        "base_url": "http://localhost:11434/v1",
        "api_key": "sk-smoke-test-not-a-real-key",
    }

    ingest = build_ingest(cfg)
    retriever = build_retriever(cfg)
    stats = index_repo(ingest, retriever)
    print(f"[ok] indexed {stats['symbols']} chunk(s) across {stats['files']} file(s) from the throwaway test repo")

    engine = build_engine(cfg, retriever=retriever)
    if not isinstance(engine.llm, OllamaLLM):
        print(f"[!!] expected engine.llm to still be OllamaLLM, got {type(engine.llm).__name__}")
        return 1
    if not isinstance(engine.code_model, OpenAICompatibleLLM):
        print(f"[!!] expected engine.code_model to be OpenAICompatibleLLM, got {type(engine.code_model).__name__}")
        return 1
    print(f"[ok] engine.llm={type(engine.llm).__name__} (native Ollama), "
          f"engine.code_model={type(engine.code_model).__name__} (OpenAI-compatible /v1)")

    result = engine.run_task(
        "Add a short comment above the greet function explaining what it does",
        thread_id="openai-compatible-smoke",
        approve=lambda plan: PlanDecision("approve"),
        approve_pr=lambda diff, title, body: False,
    )

    if result.get("approved") is not True:
        print(f"[!!] expected approved=True, got {result.get('approved')!r}")
        return 1
    print(f"[ok] plan approved (generated by llm/Ollama-native): title={result['plan'].title!r}")

    edit_results = result.get("edit_results")
    if not edit_results or any(r.get("status") != "ok" for r in edit_results):
        print(f"[!!] expected a successful edit (generated by code_model/OpenAI-compatible), got {edit_results!r}")
        return 1
    print(f"[ok] edit_results (via the OpenAI-compatible code_model adapter): {edit_results}")

    commit_result = result.get("commit_result")
    if not commit_result or commit_result.get("status") != "ok":
        print(f"[!!] expected a successful commit, got {commit_result!r}")
        return 1
    push_result = result.get("push_result")
    if not push_result or push_result.get("status") != "ok":
        print(f"[!!] expected a successful push, got {push_result!r}")
        return 1
    print(f"[ok] commit_result={commit_result}")
    print(f"[ok] push_result={push_result}")

    print("\nPhase 22 OK. Full task completed with code_model on the OpenAI-compatible "
          "adapter and llm on native Ollama -- a config-only swap, no code anywhere else changed.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
