"""Phase 14 acceptance check: runs a real task end to end (plan -> approve ->
edit), applying the plan via splice-based editing (never a model-generated
diff or whole-file rewrite for an existing symbol) and prints the resulting
diff. Confirms the edited file still parses.

Uses the same throwaway git repo as app/plan_approval_smoke_test.py, in a
separate Chroma collection. Run from the repo root:
  python -m app.plan_edit_smoke_test
"""
from __future__ import annotations
import ast
import copy
import sys
from pathlib import Path
from app.config_loader import load_config
from app.wiring import build_engine, build_ingest, build_retriever
from product.approval import PlanDecision
from product.indexing import index_repo

TEST_REPO = r"C:\Users\Ranjith\AI-Space\forge-test-repo"
TEST_CHECKPOINT_PATH = "./.data/checkpoints_plan_edit_smoke_test.db"

def main() -> int:
    base_cfg = load_config()
    cfg = copy.deepcopy(base_cfg)
    cfg["forge"]["repo_path"] = TEST_REPO
    cfg["retriever"]["collection"] = "forge_plan_edit_smoke_test"

    ingest = build_ingest(cfg)
    retriever = build_retriever(cfg)
    stats = index_repo(ingest, retriever)
    print(f"[ok] indexed {stats['symbols']} chunk(s) across {stats['files']} file(s) from the throwaway test repo")

    # Phase 20: approval_gate now uses interrupt(), which requires a real checkpointer.
    Path(TEST_CHECKPOINT_PATH).unlink(missing_ok=True)
    cfg["engine"]["checkpoint_path"] = TEST_CHECKPOINT_PATH
    engine = build_engine(cfg, retriever=retriever)
    workspace = Path(cfg["tools"]["workspace"]).resolve()

    # This run commits and pushes (Phase 17: both auto-approved, part of
    # executing an already-approved plan) but explicitly rejects at the PR
    # gate -- opening a PR is its own separate decision, out of scope for
    # this smoke test. Phase 20: omitting approve_pr entirely would PAUSE at
    # that interrupt instead of rejecting it (no callback = "nobody's
    # decided yet", not "no") -- pass one explicitly to stay in scope.
    result = engine.run_task(
        "Add a null check at the start of greet that raises ValueError if name is None",
        thread_id="plan-edit-smoke",
        approve=lambda plan: PlanDecision("approve"),
        approve_pr=lambda diff, title, body: False,
    )

    if result.get("approved") is not True:
        print(f"[!!] expected approved=True, got {result.get('approved')!r}")
        return 1
    print(f"[ok] plan approved: title={result['plan'].title!r}, branch={result['plan'].branch!r}")

    edit_results = result.get("edit_results")
    if not edit_results:
        print("[!!] expected edit_results to be present")
        return 1
    print(f"[ok] edit_results: {edit_results}")
    if any(r.get("status") not in ("ok", "unsupported", "skipped") for r in edit_results):
        print(f"[!!] at least one edit step failed: {edit_results}")
        return 1

    diff = result.get("edit_diff", "")
    if not diff.strip():
        print("[!!] expected a non-empty diff")
        return 1
    print(f"\n=== Diff (generated by difflib, not the model) ===\n{diff}")

    edited_path = workspace / "math_utils.py"
    content = edited_path.read_text(encoding="utf-8")
    try:
        ast.parse(content)
    except SyntaxError as e:
        print(f"[!!] edited file does not parse: {e}\n--- content ---\n{content}")
        return 1
    print(f"[ok] {edited_path.name} still parses as valid Python after the edit")

    # The small local code_model doesn't reliably phrase the guard the same
    # way twice (None-check vs. isinstance-check vs. falsy-check) -- accept
    # any of them, as long as it actually added a validation + raise.
    has_guard = any(marker in content for marker in ("None", "isinstance", "not name"))
    if not has_guard or "raise" not in content.lower():
        print(f"[!!] expected a validation guard to actually appear in the edited content:\n{content}")
        return 1
    print("[ok] a validation guard is actually present in the edited file")

    print(f"\n--- final file content ---\n{content}")

    # This repo has no test suite, so test_node treats "nothing to verify"
    # as a pass and the graph proceeds straight to a real commit.
    commit_result = result.get("commit_result")
    if not commit_result or commit_result.get("status") != "ok":
        print(f"[!!] expected a successful commit_result, got {commit_result!r}")
        return 1
    print(f"[ok] commit_result: {commit_result}")

    # Phase 17: commit -> push happens automatically (same "already-approved,
    # just executing" rationale as commit itself); prepare_workspace's clone
    # of TEST_REPO set 'origin' to TEST_REPO itself, so this is a real push.
    push_result = result.get("push_result")
    if not push_result or push_result.get("status") != "ok":
        print(f"[!!] expected a successful push_result, got {push_result!r}")
        return 1
    print(f"[ok] push_result: {push_result}")

    # approve_pr wasn't supplied -> defaults to reject -> stops at the PR
    # gate without ever calling open_pr (opening a PR is its own decision).
    if result.get("pr_approved") is not False:
        print(f"[!!] expected pr_approved=False (no approve_pr given), got {result.get('pr_approved')!r}")
        return 1
    if "pr_result" in result:
        print(f"[!!] open_pr should never have run, got pr_result={result['pr_result']!r}")
        return 1
    print("[ok] pr_approved=False, open_pr never ran (no approve_pr callback given)")

    print("\nPhase 14 (edit node) OK. Splice-based edit applied, backed up, diffed, parses, committed, and pushed.")
    return 0

if __name__ == "__main__":
    sys.exit(main())
